# Changes here will be overwritten by Copier
AddAllcontributors: false
AddCitationCFF: false
AddCodeOfConduct: false
AddContributionDocs: true
AddCopierCI: false
AddDocs: true
AddDocsCI: true
AddFormatterAndLinterConfigFiles: true
AddGitHubPRTemplate: false
AddGitHubTemplates: false
AddLintCI: true
AddLychee: true
AddMacToCI: false
AddPrecommit: true
AddPrecommitUpdateCI: false
AddTagBotCI: true
AddTestCI: true
AddWinToCI: false
Authors: Abel Soares Siqueira
CheckExplicitImports: false
ConfigIndentation: 2
GitHubActionVersionAutoUpdate: dependabot
JuliaCompatAutoUpdate: dependabot
JuliaIndentation: 4
JuliaMinCIVersion: lts
JuliaMinVersion: '1.10'
License: Apache-2.0
LicenseCopyrightHolders: Abel Soares Siqueira
MarkdownIndentation: 2
PackageName: TulipaBuilder
PackageOwner: TulipaEnergy
PackageUUID: 05fe4dc7-9a58-53a4-b912-b5673d74e816
RunJuliaNightlyOnCI: false
StrategyConfirmIncluded: true
StrategyLevel: 1
StrategyReviewExcluded: true
TestingStrategy: testitem_cli
UseCirrusCI: false
_commit: v0.18.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
